universe = vanilla
executable = runPython.sh


arguments = $(file)

transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/el8/python310.tar.gz, packages.tar.gz, analysis.py, fileList.txt

should_transfer_files = YES
when_to_transfer_output = ON_EXIT


error = example.err
output = example.out
log = example.log


request_cpus = 1
request_memory = 10GB
request_disk = 10GB


queue file from fileList.txt
